### ISSUE TITLE
settings.py

### ISSUE THREAD

**Issue by texmorgan** [WritingPanda/perch_demo_refresh#3]
You may want to consider using Pydantic.

The whole class would be reduced to:
```python
class Config(BaseModel):
        test_env: bool
        username: str = os.getenv("USER") or os.getenv("QA_USER")
        ....

# Usage after instantiation: config.username
```

**Comment by WritingPanda** [comment]
Used python-decouple instead. Worked better for this usecase and removed the need for a config file. Thank you for the suggestion!
